---
- name: Run data cleaner on EC2
  hosts: ec2
  become: true  # usado só para instalar dependências no sistema

  vars:
    s3_bucket_name: "auto-bucket-health-data-monitor"
    venv_path: /home/ubuntu/data_cleaner_venv
    repo_root: /home/ubuntu/atividade_CLI_arq_nuvem

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Ensure Python 3 and pip are installed
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: present

    - name: Create a virtual environment (if not exists)
      command: python3 -m venv {{ venv_path }}
      args:
        creates: "{{ venv_path }}"

    - name: Upgrade pip inside virtual environment
      command: "{{ venv_path }}/bin/pip install --upgrade pip"

    - name: Install required Python packages
      command: "{{ venv_path }}/bin/pip install wfdb pandas boto3"

    - name: Run the Python data cleaner as ubuntu user (uses EC2 IAM Role credentials)
      become: false
      command: "{{ venv_path }}/bin/python {{ repo_root }}/scripts/data_pipeline.py {{ s3_bucket_name }}"
      args:
        chdir: "{{ repo_root }}"
