---
- name: Run data cleaner on EC2
  hosts: ec2
  become: true

  vars:
    s3_bucket_name: "auto-bucket-healt-data-monitor"
    venv_path: /home/ubuntu/data_cleaner_venv

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Ensure Python 3 and pip are installed
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: present

    - name: Create a virtual environment
      command: python3 -m venv {{ venv_path }}
      args:
        creates: "{{ venv_path }}"

    - name: Upgrade pip in virtual environment
      command: "{{ venv_path }}/bin/pip install --upgrade pip"

    - name: Install Python packages in virtual environment
      command: "{{ venv_path }}/bin/pip install wfdb pandas boto3"

    - name: Run the Python data cleaner
      command: "{{ venv_path }}/bin/python /home/ubuntu/atividade_CLI_arq_nuvem/scripts/data_pipeline.py {{ s3_bucket_name }}"
