---
- name: Run data cleaner on EC2
  hosts: ec2
  become: true

  vars:
    s3_bucket_name: "auto-bucket-healt-data-monitor"

  tasks:
    - name: Ensure Python 3 and pip are installed
      ansible.builtin.yum:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install Python packages using pip
      ansible.builtin.pip:
        name:
          - wfdb
          - pandas
        executable: pip3

    - name: Run the Python data cleaner
      command: python3 /home/ubuntu/atividade_CLI_arq_nuvem/scripts/data_pipeline.py {{ s3_bucket_name }}
